### ISSUE TITLE
Bug : Player is able to attack from the bench area

### ISSUE THREAD

**Issue by z-mehta** [h0111in/PokemonGoBack#39]
@h0111in 
the player is able to attack when energy is attach to the benched pokemon.

**Comment by h0111in** [comment]
it is fixed in latest update.

**Comment by h0111in** [comment]
is not it fixed?

**Comment by z-mehta** [comment]
@h0111in  its not fixed yet....player is able to attack from bench when energy is attached.

**Comment by z-mehta** [comment]
its not fixed

**Comment by z-mehta** [comment]
i think for this bug you need to consider "area" from where the attack is executed via "executeability" method.

**Comment by h0111in** [comment]
a trainer card only can execute its ability if it is within the active turn.
I considered that on code.
please check if it works,Close the issue

**Comment by z-mehta** [comment]
yes trainer card can attack from bench............................but if we attach energy to basic pokemon on bench.............click on the ability of that benched pokemon........................the attack happened and turn changes....

**Comment by z-mehta** [comment]
#55

**Comment by h0111in** [comment]
Ok got it, i restrict them to pokemon in active and teainer from hand.

**Comment by z-mehta** [comment]
@h0111in ,, do same for the retreat ability #55

**Comment by h0111in** [comment]
it is done. check it from latest update.

**Comment by z-mehta** [comment]
update the code

**Comment by h0111in** [comment]
it is updated.

**Comment by z-mehta** [comment]
yes it is fixed.......... @h0111in  thx
